# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: ch.fhir.ig.ch-umzh-connect
canonical: http://fhir.ch/ig/ch-umzh-connect
name: CHUMZHConnect
title: 'CH UMZH Connect IG (R4)'
description: FHIR Implementation Guide for the University Medicine Zurich (UMZH) focusing on referral processes
status: active # draft | active | retired | unknown
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CHE
date: 2026-06-10
version: 1.0.0-ballot
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: ballot # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: UMZH Connect Team
contact:
  - name: UMZH Connect
    telecom:
      - system: url
        value: https://umzhconnect.ch/

dependencies:
  ch.fhir.ig.ch-core: 7.0.0-ballot # https://fhir.ch/ig/ch-core/index.html
  ch.fhir.ig.ch-emed: 6.0.0 # https://fhir.ch/ig/ch-emed/index.html
  ch.fhir.ig.ch-etoc: 3.0.1 # https://fhir.ch/ig/ch-etoc/index.html
  ch.fhir.ig.ch-orf: 3.0.2 # https://fhir.ch/ig/ch-orf/index.html
  hl7.fhir.uv.cow: 1.0.0-ballot
pages:
  index.md:
    title: Home
  core-concept-workflow-api.md:
    title: Workflow oriented API design
  core-concept-registry.md:
    title: Registry
  workflow-states.md:
    title: Workflow States
  usecase-referral-orthopedic.md:
    title: Referral - Orthopedic Surgery
  usecase-referral-sarcoma-tumorboard.md:
    title: Referral - Sarcoma Tumor Board
  security.md:
    title: Security
  guidance-reference-architecture.md:
    title: Reference Architecture
  security-implementation.md:
    title: Security Implementation
  changelog.md:
    title: Changelog
  guidance-interactions.md:
    title: Interactions

menu:
  Home: index.html
  Core Concept:
    Workflow oriented API design: core-concept-workflow-api.html
    Registry: core-concept-registry.html
    Workflow States: workflow-states.html
    Interactions: guidance-interactions.html
  Use Cases:
    Referral - Orthopedic Surgery: usecase-referral-orthopedic.html
    Referral - Sarcoma Tumor Board: usecase-referral-sarcoma-tumorboard.html
  Security: security.html
  Implementation Notes:
    Reference Architecture: guidance-reference-architecture.html
    Security Implementation: security-implementation.html
  Artifacts: artifacts.html

# Parameters
# Core FHIR: http://build.fhir.org/codesystem-guide-parameter-code.html
# FHIR Tools IG: http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  excludettl: true
  allow-extensible-warnings: true
  display-warnings: true
  path-expansion-params: '../../expansion-params.json' # for using SNOMED CT Swiss Extension
  pin-canonicals: pin-multiples
  path-resource:
    - input/resources

FSHOnly: false
applyExtensionMetadataToRoot: false
instanceOptions:
  setMetaProfile: always
  setId: always
  manualSliceOrdering: true
