# docker-compose.yml
services:
  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"  # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  hapi-fulfiller:
    image: hapiproject/hapi:latest
    environment:
      - "hapi.fhir.allow_external_references=true"
    labels:
      - "traefik.http.routers.fulfiller.rule=Host(`fulfiller.example.org`)"
      - "traefik.http.services.fulfiller.loadbalancer.server.port=8080"

  hapi-placer:
    image: hapiproject/hapi:latest
    environment:
      - "hapi.fhir.allow_external_references=true"
    labels:
      - "traefik.http.routers.placer.rule=Host(`placer.example.org`)"
      - "traefik.http.services.placer.loadbalancer.server.port=8080"